### ISSUE TITLE
通过docker部署，浏览器访问验证时报错Attempting to use uninitialized value output_layer

### ISSUE THREAD

**Issue by liuyp2003** [pakrchen/text-antispam#5]
访问http://127.0.0.1/predict?text=%E5%8A%A0%E6%88%91%E5%BE%AE%E4%BF%A1xxxxx%E6%9C%89%E7%A6%8F%E5%88%A9
错误代码：
ERROR:tornado.application:Uncaught exception GET /predict?text=%E5%8A%A0%E6%88%91%E5%BE%AE%E4%BF%A1xxxxx%E6%9C%89%E7%A6%8F%E5%88%A9 (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1', method='GET', uri='/predict?text=%E5%8A%A0%E6%88%91%E5%BE%AE%E4%BF%A1xxxxx%E6%9C%89%E7%A6%8F%E5%88%A9', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "E:\ProgramFiles\Python35\lib\site-packages\grpc\beta\_client_adaptations.py", line 193, in _blocking_unary_unary
    credentials=_credentials(protocol_options))
  File "E:\ProgramFiles\Python35\lib\site-packages\grpc\_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "E:\ProgramFiles\Python35\lib\site-packages\grpc\_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.FAILED_PRECONDITION
	details = "Attempting to use uninitialized value output_layer/b
	 [[{{node output_layer/b/read}} = Identity[T=DT_FLOAT, _output_shapes=[[2]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](output_layer/b)]]"
	debug_error_string = "{"created":"@1541404487.436000000","description":"**Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Attempting to use uninitialized** value output_layer/b\n\t [[{{node output_layer/b/read}} = Identity[T=DT_FLOAT, _output_shapes=[[2]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](output_layer/b)]]","grpc_status":9}"
>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "E:\ProgramFiles\Python35\lib\site-packages\tornado\web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "E:/docker/text-antispam-master/serving/serving.py", line 21, in get
    predict = self.classify(text)
  File "E:/docker/text-antispam-master/serving/serving.py", line 38, in classify

**### tensorflow serving启动后：**
docker@tfServing-docker:~$ docker run -it -p 9000:9000 -v /docker:/docker tensorflow/serving:latest-devel
root@0a2946e3e077:/tensorflow-serving# tensorflow_model_server --port=9000 --model_base_path=/docker/model --model_name=saved_model
2018-11-05 03:19:46.464088: I tensorflow_serving/model_servers/server.cc:82] Building single TensorFlow model file config:  model_name: saved_model model_base_path: /docker/model
2018-11-05 03:19:46.465177: I tensorflow_serving/model_servers/server_core.cc:462] Adding/updating models.
2018-11-05 03:19:46.466121: I tensorflow_serving/model_servers/server_core.cc:517]  (Re-)adding model: saved_model
2018-11-05 03:19:46.575415: I tensorflow_serving/core/basic_manager.cc:739] Successfully reserved resources to load servable {name: saved_model version: 1}
2018-11-05 03:19:46.578178: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: saved_model version: 1}
2018-11-05 03:19:46.580695: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: saved_model version: 1}
2018-11-05 03:19:46.583750: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /docker/model/1
2018-11-05 03:19:46.585615: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /docker/model/1
2018-11-05 03:19:46.593028: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2018-11-05 03:19:46.615678: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:162] Restoring SavedModel bundle.
2018-11-05 03:19:46.617201: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:172] The specified SavedModel has no variables; no checkpoints were restored. File does not exist: /docker/model/1/variables/variables.index
2018-11-05 03:19:46.618343: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:138] Running MainOp with key legacy_init_op on SavedModel bundle.
2018-11-05 03:19:46.619315: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:259] SavedModel load for tags { serve }; Status: success. Took 33692 microseconds.
2018-11-05 03:19:46.620873: I tensorflow_serving/servables/tensorflow/saved_model_warmup.cc:83] No warmup data file found at /docker/model/1/assets.extra/tf_serving_warmup_requests
2018-11-05 03:19:46.627259: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: saved_model version: 1}
2018-11-05 03:19:46.630992: I tensorflow_serving/model_servers/server.cc:285] Running gRPC ModelServer at 0.0.0.0:9000 ...

**### 客户端启动serving.py后**
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
runfile('E:/docker/text-antispam-master/serving/serving.py', wdir='E:/docker/text-antispam-master/serving')
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
DEBUG:jieba:Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
Loading model cost 1.188 seconds.
DEBUG:jieba:Loading model cost 1.188 seconds.
Prefix dict has been built succesfully.
DEBUG:jieba:Prefix dict has been built succesfully.
分词 初始化
listen start
### 
**代码修改处**
host, port = ('192.168.99.100', '9000')
channel = implementations.insecure_channel(host, int(port))
stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
request = predict_pb2.PredictRequest()
request.model_spec.name = 'saved_model'

**Comment by liuyp2003** [comment]
不知道问题是不是有描述清楚了。
